// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// entropypluginC
double entropypluginC(NumericVector x, String unit);
RcppExport SEXP entropC_entropypluginC(SEXP xSEXP, SEXP unitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type unit(unitSEXP);
    __result = Rcpp::wrap(entropypluginC(x, unit));
    return __result;
END_RCPP
}
// entropyMMC
double entropyMMC(NumericVector x, String unit);
RcppExport SEXP entropC_entropyMMC(SEXP xSEXP, SEXP unitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type unit(unitSEXP);
    __result = Rcpp::wrap(entropyMMC(x, unit));
    return __result;
END_RCPP
}
// entropyChaoShenC
double entropyChaoShenC(NumericVector x, String unit);
RcppExport SEXP entropC_entropyChaoShenC(SEXP xSEXP, SEXP unitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type unit(unitSEXP);
    __result = Rcpp::wrap(entropyChaoShenC(x, unit));
    return __result;
END_RCPP
}
