# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chi2indepC <- function(x) {
    .Call('entropC_chi2indepC', PACKAGE = 'entropC', x)
}

chi2pluginC <- function(x, y, unit = "log") {
    .Call('entropC_chi2pluginC', PACKAGE = 'entropC', x, y, unit)
}

entropyChaoShenC <- function(x, unit = "log") {
    .Call('entropC_entropyChaoShenC', PACKAGE = 'entropC', x, unit)
}

entropyMMC <- function(x, unit = "log") {
    .Call('entropC_entropyMMC', PACKAGE = 'entropC', x, unit)
}

entropypluginC <- function(x, unit = "log") {
    .Call('entropC_entropypluginC', PACKAGE = 'entropC', x, unit)
}

freqsshrinkC <- function(y, lambda) {
    .Call('entropC_freqsshrinkC', PACKAGE = 'entropC', y, lambda)
}

freqsdirichletC <- function(x, a) {
    .Call('entropC_freqsdirichletC', PACKAGE = 'entropC', x, a)
}

freqsempiricalC <- function(x) {
    .Call('entropC_freqsempiricalC', PACKAGE = 'entropC', x)
}

getlambdashrinkC <- function(y) {
    .Call('entropC_getlambdashrinkC', PACKAGE = 'entropC', y)
}

KLpluginC <- function(x, y, unit = "log") {
    .Call('entropC_KLpluginC', PACKAGE = 'entropC', x, y, unit)
}

mipluginC <- function(x, unit = "log") {
    .Call('entropC_mipluginC', PACKAGE = 'entropC', x, unit)
}

