# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropypluginC <- function(x, unit = "log") {
    .Call('entropC_entropypluginC', PACKAGE = 'entropC', x, unit)
}

entropyMMC <- function(x, unit = "log") {
    .Call('entropC_entropyMMC', PACKAGE = 'entropC', x, unit)
}

entropyChaoShenC <- function(x, unit = "log") {
    .Call('entropC_entropyChaoShenC', PACKAGE = 'entropC', x, unit)
}

